### ISSUE TITLE
version of asterisk

### ISSUE THREAD

**Issue by masteringvoip** [nadirhamid/asterisk-audiofork#11]
Hi Sir,

Can you help, in what version asterisk audifork working?

Thanks

**Comment by masteringvoip** [comment]
Hi Sir,

It nor working on asterisk 1.8.2.3

app_audiofork.c:57:35: fatal error: asterisk/format_cache.h: No such file or directory
 #include "asterisk/format_cache.h"
                                   ^
compilation terminated.
make[1]: *** [app_audiofork.o] Error 1
make: *** [apps] Error 2

**Comment by nadirhamid** [comment]
@masteringvoip 

It was tested for Asterisk version 16 and higher. Although I have not tested latest versions, I am assuming it would work for any new release. I would recommend upgrading your Asterisk version if possible, otherwise it will likely not work.

If you have any other questions or need more info let me know.

Thanks
